language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=Django==1.4.22
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.11
  - DJANGO=Django==1.7.11
  - DJANGO=Django==1.8.9
  - DJANGO=Django==1.9.2

install:
  - pip install -q $DJANGO

script:
  - PYTHONPATH=$PYTHONPATH:$PWD django-admin.py test axes --settings=axes.test_settings

matrix:
    exclude:
        - python: 3.3
          env: DJANGO=Django==1.4.22
        - python: 3.4
          env: DJANGO=Django==1.4.22
